const D=window.ALBERTSONS_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const masters=[window.ALBERTSONS_BANNER_STORES,window.ALBERTSONS_TOM_THUMB_STORES,window.ALBERTSONS_RANDALLS_STORES,window.ALBERTSONS_UNITED_STORES].filter(Boolean).flat();
if(masters.length)D.stores=masters.map(s=>({...s,instock:null,delta:null,oos:null}));
const saved=JSON.parse(localStorage.getItem('albertsons-item-actions')||'{}');D.items.forEach(i=>{if(saved[i.id])Object.assign(i,saved[i.id])});
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),pct=n=>Number.isFinite(n)?`${n.toFixed(1)}%`:'—',deliveryText=s=>Array.isArray(s.delivery)?s.delivery.join(', '):s.delivery||'—';
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}function save(){const o={};D.items.forEach(i=>o[i.id]={status:i.status,qty:i.qty});localStorage.setItem('albertsons-item-actions',JSON.stringify(o))}function status(v){if(!Number.isFinite(v))return'pending';return v>=97?'green':v>=93?'watch':'critical'}function statusLabel(v){return Number.isFinite(v)?status(v).toUpperCase():'AWAITING DATA'}
function setView(n){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(b=>b.classList.remove('active'));$(`#${n}View`).classList.add('active');$(`.nav-item[data-view="${n}"]`)?.classList.add('active');$('#pageTitle').textContent={overview:'In-Stock Overview',stores:'Store Execution',items:'Item Tracker',sales:'Added Sales',schedule:'Field Schedule'}[n];$('#sidebar').classList.remove('open');if(n==='sales')renderSales()}$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#todayLabel').textContent=new Date().toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
function deliveryCounts(){const days=['Mon','Tue','Wed','Thu','Fri'],out=Object.fromEntries(days.map(d=>[d,0]));D.stores.forEach(s=>(Array.isArray(s.delivery)?s.delivery:[s.delivery]).filter(Boolean).forEach(d=>{if(out[d]!=null)out[d]++}));return out}
function renderOverview(){const valid=D.stores.filter(s=>Number.isFinite(s.instock)),avg=valid.length?valid.reduce((a,b)=>a+b.instock,0)/valid.length:null;$('#heroInstock').textContent=$('#kpiInstock').textContent=pct(avg);$('#kpiGap').textContent=valid.length?`${(98.5-avg).toFixed(1)} pts gap`:'Awaiting feed';$('#kpiGreen').textContent=D.stores.length;$('#greenPct').textContent=`${new Set(D.stores.map(s=>s.banner)).size} banners`;$('#sidebarGap').textContent=valid.length?`Current gap: ${(98.5-avg).toFixed(1)} pts`:'Awaiting in-stock feed';$('#sidebarProgress').style.width=valid.length?`${Math.min(100,avg/98.5*100)}%`:'0%';$('#heroSub').textContent=valid.length?'Live network performance':'Awaiting in-stock feed';
$('#overviewStoreRows').innerHTML=D.stores.slice(0,12).map(s=>`<tr><td><strong>${s.name}</strong><br><small>${s.address||''}</small></td><td>${s.banner||'—'}</td><td>${s.market||'—'}</td><td>${s.city||'—'}</td><td><strong>${deliveryText(s)}</strong></td></tr>`).join('');
const bannerCounts={};D.stores.forEach(s=>bannerCounts[s.banner]=(bannerCounts[s.banner]||0)+1);$('#priorityList').innerHTML=Object.entries(bannerCounts).sort((a,b)=>b[1]-a[1]).map(([b,n])=>`<div class="priority-item"><span class="priority-dot"></span><div class="priority-main"><strong>${b}</strong><span>Texas store master</span></div><b>${n}</b></div>`).join('');
const dc=deliveryCounts(),max=Math.max(...Object.values(dc),1);$('#dowBars').innerHTML=Object.entries(dc).map(([d,n])=>`<div class="bar-row"><strong>${d}</strong><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%"></div></div><strong>${n}</strong></div>`).join('');
const markets={};D.stores.forEach(s=>markets[s.market]=(markets[s.market]||0)+1);$('#marketMix').innerHTML=Object.entries(markets).sort((a,b)=>b[1]-a[1]).map(([m,n])=>`<div class="impact-item"><div class="impact-top"><span>${m}</span><strong>${n} stores</strong></div><div class="impact-bar"><div style="width:${n/D.stores.length*100}%"></div></div></div>`).join('')}
function fillFilters(){[...new Set(D.stores.map(s=>s.banner).filter(Boolean))].sort().forEach(v=>$('#bannerFilter').insertAdjacentHTML('beforeend',`<option>${v}</option>`));[...new Set(D.stores.map(s=>s.market).filter(Boolean))].sort().forEach(v=>$('#marketFilter').insertAdjacentHTML('beforeend',`<option>${v}</option>`));[...new Set(D.stores.map(s=>s.city).filter(Boolean))].sort().forEach(v=>$('#cityFilter').insertAdjacentHTML('beforeend',`<option>${v}</option>`));[...new Set(D.items.map(i=>i.category))].sort().forEach(c=>$('#categoryFilter').insertAdjacentHTML('beforeend',`<option>${c}</option>`))}
function renderStores(){const banner=$('#bannerFilter').value,market=$('#marketFilter').value,city=$('#cityFilter').value,q=$('#globalSearch').value.toLowerCase();const a=D.stores.filter(s=>(banner==='all'||s.banner===banner)&&(market==='all'||s.market===market)&&(city==='all'||s.city===city)&&(!q||`${s.name} ${s.banner} ${s.market} ${s.city} ${s.address} ${s.id}`.toLowerCase().includes(q)));$('#storeRows').innerHTML=a.map(s=>`<tr><td><strong>${s.name}</strong><br><small>${s.id}</small></td><td>${s.banner||'—'}</td><td>${s.market||'—'}</td><td>${s.city||'—'}</td><td>${s.address||'—'}</td><td><strong>${deliveryText(s)}</strong></td><td>${pct(s.instock)}</td><td><span class="pill ${status(s.instock)}">${statusLabel(s.instock)}</span></td></tr>`).join('')||'<tr><td colspan="8">No stores match.</td></tr>'}
function renderItems(){const c=$('#categoryFilter').value,st=$('#itemStatusFilter').value,q=$('#globalSearch').value.toLowerCase(),a=D.items.filter(i=>(c==='all'||i.category===c)&&(st==='all'||i.status===st)&&(!q||`${i.item} ${i.store} ${i.category}`.toLowerCase().includes(q)));$('#itemRows').innerHTML=a.map(i=>`<tr><td><span class="pill ${i.priority==='High'?'critical':i.priority==='Medium'?'watch':'green'}">${i.priority}</span></td><td><strong>${i.item}</strong></td><td>${i.category}</td><td>${i.store}</td><td><strong>${pct(i.instock)}</strong></td><td><select onchange="updateStatus(${i.id},this.value)">${['Open','Added','Verified'].map(v=>`<option ${i.status===v?'selected':''}>${v}</option>`).join('')}</select></td><td><select class="qty-select" onchange="updateQty(${i.id},this.value)">${[0,1,2,3,4,5].map(n=>`<option ${i.qty===n?'selected':''}>${n}</option>`).join('')}</select></td><td>${money(i.casePrice)}</td><td class="money">${money(i.qty*i.casePrice)}</td></tr>`).join('')||'<tr><td colspan="9">Item-level feed not loaded yet.</td></tr>';renderImpact()}
window.updateStatus=(id,v)=>{D.items.find(x=>x.id===id).status=v;save();toast(`Status updated: ${v}`)};window.updateQty=(id,v)=>{const i=D.items.find(x=>x.id===id);i.qty=+v;if(i.qty&&i.status==='Open')i.status='Added';save();renderItems();toast(`${i.qty} case${i.qty===1?'':'s'} added • ${money(i.qty*i.casePrice)}`)};
function impact(){const a=D.items.filter(i=>i.qty>0),cases=a.reduce((x,i)=>x+i.qty,0),dollars=a.reduce((x,i)=>x+i.qty*i.casePrice,0);return{a,cases,dollars}}function renderImpact(){const x=impact();$('#kpiCases').textContent=x.cases;$('#kpiDollars').textContent=money(x.dollars);$('#caseTrend').textContent=x.cases?'Captured this session':'Ready to track';$('#dollarTrend').textContent=x.dollars?`${x.a.length} items actioned`:'Live'}
function renderSales(){const x=impact();$('#salesCases').textContent=x.cases;$('#salesDollars').textContent=money(x.dollars);$('#salesItems').textContent=x.a.length;$('#salesAvg').textContent=money(x.a.length?x.dollars/x.a.length:0);const c={};x.a.forEach(i=>c[i.category]=(c[i.category]||0)+i.qty*i.casePrice);$('#categoryImpact').innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="impact-item"><div class="impact-top"><span>${k}</span><strong>${money(v)}</strong></div><div class="impact-bar"><div style="width:${x.dollars?v/x.dollars*100:0}%"></div></div></div>`).join('')||'<small>Add cases in Item Tracker to populate this analysis.</small>';const detail=$('#salesDetailRows');if(detail)detail.innerHTML=x.a.length?x.a.sort((a,b)=>b.qty*b.casePrice-a.qty*a.casePrice).map(i=>`<tr><td><strong>${i.item}</strong></td><td>${i.store}</td><td>${i.category}</td><td><strong>${i.qty}</strong></td><td class="money">${money(i.casePrice)}</td><td class="money">${money(i.qty*i.casePrice)}</td></tr>`).join(''):'<tr><td colspan="6"><small>Add cases in Item Tracker to see store and item detail here.</small></td></tr>';drawBars($('#salesChart'),[0,0,0,0,0,0,x.dollars],['Thu','Fri','Sat','Sun','Mon','Tue','Wed'])}
function renderSchedule(){const days=['Mon','Tue','Wed','Thu','Fri'];$('#scheduleGrid').innerHTML=days.map(day=>{const stores=D.stores.filter(s=>(Array.isArray(s.delivery)?s.delivery:[s.delivery]).includes(day));return`<article class="schedule-day"><h3>${day}</h3><div class="schedule-date">${stores.length} delivery stop${stores.length===1?'':'s'}</div>${stores.slice(0,14).map(s=>`<div class="schedule-event"><strong>${s.name}</strong><span>${s.market} • ${s.city}</span></div>`).join('')}${stores.length>14?`<div class="schedule-event"><strong>+ ${stores.length-14} more</strong><span>Use Store Execution filters for full list</span></div>`:''}</article>`}).join('')}
function prep(c){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);return{x,w:r.width,h:r.height}}function drawBars(c,v,l){if(!c)return;const{x,w,h}=prep(c),max=Math.max(...v,100),slot=(w-40)/v.length;x.clearRect(0,0,w,h);v.forEach((n,i)=>{const bh=n/max*(h-40);x.fillStyle='#00529b';x.fillRect(30+i*slot+slot*.2,h-28-bh,slot*.6,bh);x.fillStyle='#8b93a1';x.font='10px Inter';x.fillText(l[i],30+i*slot+slot*.2,h-8)})}
function exportCSV(){const r=[['Store','Banner','Market','City','Address','Longitude','Latitude','Delivery Days','In-Stock'],...D.stores.map(s=>[s.name,s.banner,s.market,s.city,s.address,s.lng,s.lat,deliveryText(s),Number.isFinite(s.instock)?s.instock:''])],csv=r.map(a=>a.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),b=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='Albertsons-Texas-Store-Master.csv';a.click();toast('Store master exported')}
$('#exportBtn').onclick=exportCSV;['bannerFilter','marketFilter','cityFilter'].forEach(id=>$(`#${id}`).onchange=renderStores);['categoryFilter','itemStatusFilter'].forEach(id=>$(`#${id}`).onchange=renderItems);$('#globalSearch').oninput=()=>{renderStores();renderItems()};window.addEventListener('resize',()=>{renderOverview();if($('#salesView').classList.contains('active'))renderSales()});fillFilters();renderOverview();renderStores();renderItems();renderSchedule();